services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5435:5435
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
      - PGPORT= 5435
