services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5435:5435
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
      - PGPORT=5435
  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: next
    ports:
      - 3000:3000
  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
      target: fastify-api
    ports:
      - 3939:3939
    environment:
      - HOST=0.0.0.0
